name: CI/CD - Train & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest

    env:
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Train model and log to DagsHub
      - name: Train model
        run: |
          set -e
          python src/train_model.py

      # 5. Deploy to Render
      - name: Deploy to Render
        run: |
          set -e
          curl -X POST "https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
